baseURL = "/"
copyright = "All rights reserved - 2018"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en"
paginate = 5
theme = "hugo-theme-casper"
title = "AMBA Business School Search Test"
[params]
author = "YOUR_NAME"
authorbio = ""
authorlocation = "Earth, Milky Way Galaxy"
authorwebsite = ""
cover = "/img/darius-soodmand-116253.jpg"
description = "Search for a programme"
hjsstyle = "default"
logo = ""
metadescription = "The place to find your MBA programme"
paginatedsections = ["posts"]
